language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: true
install:
  - pip install tox
script:
  - tox
after_success:
    - coveralls
