language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37
install:
  - pip install tox
script:
  - tox
after_success:
    - coveralls
