dist: xenial
language: python
cache: pip

before_script:
  - pip install tox

script: tox

matrix:
  fast_finish: true
  include:

    - python: "3.5"
      env: TOXENV=py35

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.5"
      env: TOXENV=py35-pylint

    - python: "3.6"
      env: TOXENV=py36-pylint
