language : python

python:
    - python: 2.6
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: pypy
     
script:
    - echo "TODO"
