language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

install:
  - pip install tox
script:
  - tox
after_success:
    - coveralls

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
    - python: 3.8

    - python: 3.8
      env: TOXENV=docs

    - python: 3.8
      env: TOXENV=desc
      
