language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3
jobs:
  include:
    - name: flake8
      install: pip install tox
      script: tox -e flake8
      after_script:
    - name: mypy
      install: pip install tox
      script: tox -e mypy
      after_script:
    - name: isort
      install: pip install tox
      script: tox -e isort
      after_script:
install:
  - pip install tox
script:
  - tox
after_success:
    - coveralls
